project:
  type: website
  render:
    - index.qmd
    - books.qmd
    - articles.qmd
    - teaching.qmd

website:
  title: "Sabri Ciftci"
  navbar:
    background: white
    foreground: dark
    left:
      - href: index.qmd
        text: Home
      - href: books.qmd
        text: Books
      - href: articles.qmd
        text: Articles
      - href: teaching.qmd
        text: Teaching
  page-footer:
    center: |
      [ciftci@ksu.edu](mailto:ciftci@ksu.edu)

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,300;0,400;0,600;1,400&display=swap" rel="stylesheet">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
